spring:
  profiles:
    active: local
server:
  port: 80
logging:
  file:
    name: ./logs/learn-spring-boot-reactive.log
    path: ./logs
---
spring:
  profiles: local
---
spring:
  profiles: dev
---
spring:
  profiles: production